# Generated by Django 4.2.5 on 2023-10-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
                ('Password', models.CharField(blank=True, max_length=20, null=True)),
                ('Username', models.CharField(blank=True, max_length=20, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
