# Generated by Django 4.2.5 on 2023-09-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='catdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=20, null=True)),
                ('Description', models.CharField(blank=True, max_length=20, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='dp')),
            ],
        ),
        migrations.DeleteModel(
            name='adddb',
        ),
    ]
